import { GetServerSideProps } from "next";
import { Inter } from "next/font/google";
import Head from "next/head";
import { AppConfigKeys, getAppConfig } from "../appConfig";
import Section from "./components/Section";
import FloatFooter from "./features/FloatFooter";
import Footer from "./features/Footer";
import Header from "./features/Header";
import SectionAutomtiveService from "./features/SectionAutomtiveService";
import SectionFirst from "./features/SectionFirst";
import SectionResidentialService from "./features/SectionResidentialService";
import SectionService from "./features/SectionService";
import { useEffect } from "react";
import  DomainContext  from "./components/DomainContext";

type Props = {
  domain: AppConfigKeys;
};

export const getServerSideProps = (async () => {
  return {
    props: {
      domain: "dayandnightlocksmith.com",
    },
  };
}) satisfies GetServerSideProps<Props>;

export default function Home({ domain }: Props) {
  useEffect(() => {
    console.warn("Domain", domain);
  }, []);
  return (
    <>
      <Head>
        <title>{getAppConfig(domain).name}</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />

        {/* fonts */}
        <link rel="preconnect" href="https://fonts.googleapis.com" />
        <link rel="preconnect" href="https://fonts.gstatic.com" />
        <link
          href="https://fonts.googleapis.com/css2?family=IBM+Plex+Sans:ital,wght@0,100;0,200;0,300;0,400;0,500;0,600;0,700;1,100;1,200;1,300;1,400;1,500;1,600;1,700&display=swap"
          rel="stylesheet"
        ></link>
      </Head>
      <main>
        <DomainContext.Provider value={{ domain }}>
          <Header />
          <SectionFirst />
          <Section bg="asset1.webp" />
          <SectionService />
          <SectionResidentialService />
          <SectionAutomtiveService />
          <Footer />
          <FloatFooter />
        </DomainContext.Provider>
      </main>
    </>
  );
}
